# _config.yml - Jekyll Configuration
#
# @author: Cade Brown <me@cade.site>

# site settings
title: Kata
description: "Kata lets you build software applications and libraries in a completely cross platform way"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kata.wiki"

# links/socials
email: info@kata.wiki
twitter: katadotwiki
github: katawiki

# blog permalinks
permalink: /blog/:title

# renderer settings
markdown: kramdown
kramdown:
  parse_block_html: true
  # disable the default syntax highligher (since we use Prism.js)
  syntax_highlighter_opts:
    disable: true
plugins:
  - jekyll-paginate
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      use_prism: true
      use_katex: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
